version: '3'

services:
  app:
    build: .
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=litra
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=litra
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
