INSERT INTO book_category (name) VALUES ('Как писать хорошо, а нехорошо не писать');
INSERT INTO book_category (name) VALUES ('Тестирование');
INSERT INTO book_category (name) VALUES ('Python');
INSERT INTO book_category (name) VALUES ('Go');
INSERT INTO book_category (name) VALUES ('Rust');
INSERT INTO book_category (name) VALUES ('JavaScript');
INSERT INTO book_category (name) VALUES ('Linux ');
INSERT INTO book_category (name) VALUES ('Алгоритмы');
INSERT INTO book_category (name) VALUES ('БД');
INSERT INTO book_category (name) VALUES ('Безопасность');
INSERT INTO book_category (name) VALUES ('Большие системы');
INSERT INTO book_category (name) VALUES ('Фронтенд');
INSERT INTO book_category (name) VALUES ('Machine Learning');
INSERT INTO book_category (name) VALUES ('Another interesting');
INSERT INTO book_category (name) VALUES ('Софт-скилы, проектная работа');
INSERT INTO book_category (name) VALUES ('Дизайн');
INSERT INTO book (name, category_id, ordering) VALUES ('Чистый код :: Роберт Мартин', 1, 1);
INSERT INTO book (name, category_id, ordering) VALUES ('Идеальный программист :: Роберт Мартин', 1, 2);
INSERT INTO book (name, category_id, ordering) VALUES ('Чистая архитектура :: Роберт Мартин', 1, 3);
INSERT INTO book (name, category_id, ordering) VALUES ('Идеальная работа :: Роберт Мартин', 1, 4);
INSERT INTO book (name, category_id, ordering) VALUES ('Совершенный код :: Стив Макконнелл', 1, 5);
INSERT INTO book (name, category_id, ordering) VALUES ('Паттерны объектно-ориентированного проектирования :: Гамма Эрих, Хелм Ричард, Джонсон Роберт, Влиссидес Джон', 1, 6);
INSERT INTO book (name, category_id, ordering) VALUES ('Head First. Паттерны проектирования. 2-е издание :: Эрик Фримен, Элизабет Робсон', 1, 7);
INSERT INTO book (name, category_id, ordering) VALUES ('Шаблоны корпоративных приложений :: Мартин Фаулер', 1, 8);
INSERT INTO book (name, category_id, ordering) VALUES ('Шаблоны интеграции корпоративных приложений :: Бобби Вульф, Грегор Хоп', 1, 9);
INSERT INTO book (name, category_id, ordering) VALUES ('Предметно-ориентированное проектирование :: Эрик Эванс', 1, 10);
INSERT INTO book (name, category_id, ordering) VALUES ('Реализация методов предметно-ориентированного проектирования :: Вон Вернон', 1, 11);
INSERT INTO book (name, category_id, ordering) VALUES ('Пять строк кода :: Кристиан Клаусен', 1, 12);
INSERT INTO book (name, category_id, ordering) VALUES ('Рефакторинг. Улучшение существующего кода :: Мартин Фаулер ', 1, 13);
INSERT INTO book (name, category_id, ordering) VALUES ('Программируй & типизируй :: Влад Ришкуция', 1, 14);
INSERT INTO book (name, category_id, ordering) VALUES ('A Philosophy of Software Design, 2nd edition :: John Ousterhout', 1, 15);
INSERT INTO book (name, category_id, ordering) VALUES ('Эффективная работа с унаследованным кодом :: Майкл Физерс', 1, 16);
insert into book (name, category_id, ordering) values ('Экстремальное программирование: разработка через тестирование :: Бек Кент', 2, 1);
insert into book (name, category_id, ordering) values ('Принципы юнит-тестирования :: Хориков Владимир', 2, 2);
insert into book (name, category_id, ordering) values ('Python. Разработка на основе тестирования :: Персиваль Гарри', 2, 3);
insert into book (name, category_id, ordering) values ('Эффективное тестирование программного обеспечения :: Аниче Маурисио', 2, 4);
insert into book (name, category_id, ordering) values ('Начинаем Программировать на Python. 5 издание :: Тонни Гэддис', 3, 1);
insert into book (name, category_id, ordering) values ('Простой Python. 2 издание :: Билл Любанович', 3, 2);
insert into book (name, category_id, ordering) values ('Effective Python: 90 Specific Ways to Write Better Python :: Brett Slatkin', 3, 3);
insert into book (name, category_id, ordering) values ('Python на практике :: Марк Саммерфильд', 3, 4);
insert into book (name, category_id, ordering) values ('Python к вершинам мастерства :: Лучано Рамальо', 3, 5);
insert into book (name, category_id, ordering) values ('Asyncio и конкурентное программирование :: Мэттью Фаулер', 3, 6);
insert into book (name, category_id, ordering) values ('Паттерны разработки на Python :: Гарри Персиваль. Боб Грегори', 3, 7);
insert into book (name, category_id, ordering) values ('Clean Code in Python, Second Edition :: Mariano Anaya', 3, 8);
insert into book (name, category_id, ordering) values ('Python Tricks :: Dan Bader, он же Чистый Python тонкости программирования для профи', 3, 9);
insert into book (name, category_id, ordering) values ('Высокопроизводительные Python-приложения. Практическое руководство по эффективному программированию, 2 издание :: Горелик Миша', 3, 10);
insert into book (name, category_id, ordering) values ('Автоматизация рутинных задач с помощью Python. 2 издание :: Эл Свейгарт', 3, 11);
insert into book (name, category_id, ordering) values ('Внутри CPYTHON: гид по интерпретатору Python :: Энтони Шоу', 3, 12);
insert into book (name, category_id, ordering) values ('Стандартная библиотека Python 3. Справочник с примерами :: Хеллман Даг', 3, 13);
insert into book (name, category_id, ordering) values ('Язык программирования Go :: Алан Донован, Брайан Керниган', 4, 1);
insert into book (name, category_id, ordering) values ('Go на практике :: Мэтт Батчер, Мэтт Фарина', 4, 2);
insert into book (name, category_id, ordering) values ('Go. Идиомы и паттерны проектирования :: Джон Боднер', 4, 3);
insert into book (name, category_id, ordering) values ('Программирование на Rust. Официальный гайд', 5, 1);
insert into book (name, category_id, ordering) values ('Программирование на языке Rust :: Джейсон Орендорф, Джим Блэнди', 5, 2);
insert into book (name, category_id, ordering) values ('Rust в действии :: Тим Макнамара', 5, 3);
insert into book (name, category_id, ordering) values ('Zero To Production In Rust :: Luca Palmieri', 5, 4);
insert into book (name, category_id, ordering) values ('Выразительный JavaScript. Современное веб-программирование :: Хавербеке Марейн', 6, 1);
insert into book (name, category_id, ordering) values ('Вы не знаете JS: Начните и Совершенствуйтесь :: Kyle Simpson', 6, 2);
insert into book (name, category_id, ordering) values ('Вы не знаете JS: Область видимости и замыкания :: Kyle Simpson', 6, 3);
insert into book (name, category_id, ordering) values ('Вы не знаете JS: this и Прототипы Объектов :: Kyle Simpson', 6, 4);
insert into book (name, category_id, ordering) values ('Вы не знаете JS: Типы и грамматика :: Kyle Simpson', 6, 5);
insert into book (name, category_id, ordering) values ('Вы не знаете JS: Асинхронность и Производительность :: Kyle Simpson', 6, 6);
insert into book (name, category_id, ordering) values ('Вы не знаете JS: ES6 и не только :: Kyle Simpson', 6, 7);
insert into book (name, category_id, ordering) values ('Тестирование JavaScript :: Лукас Коста', 6, 8);
insert into book (name, category_id, ordering) values ('Командная строка Linux. Полное руководство :: Шоттс Уильям', 7, 1);
insert into book (name, category_id, ordering) values ('Linux. Необходимый код и команды :: Граннеман Скотт', 7, 2);
insert into book (name, category_id, ordering) values ('Библия Linux. 10-е издание :: Негус Кристофер', 7, 3);
insert into book (name, category_id, ordering) values ('Грокаем алгоритмы :: Бхаргава Адитья', 8, 1);
insert into book (name, category_id, ordering) values ('Алгоритмы для начинающих. Теория и практика для разработчика :: Луридас Панос (проще Кормена, глубже, чем Грокаем)', 8, 2);
insert into book (name, category_id, ordering) values ('Алгоритмы: построение и анализ. 3-е издание :: Томас Кормен', 8, 3);
insert into book (name, category_id, ordering) values ('Тим Рафгарден, серия Совершенный алгоритм', 8, 4);
insert into book (name, category_id, ordering) values ('Основы технологий баз данных :: Борис Новиков, Екатерина Горшкова', 9, 1);
insert into book (name, category_id, ordering) values ('PostgreSQL 14 изнутри :: Егор Рогов', 9, 2);
insert into book (name, category_id, ordering) values ('Оптимизация запросов в PostgreSQL :: Борис Новиков, Генриэтта Домбровская', 9, 3);
insert into book (name, category_id, ordering) values ('PostgreSQL. Основы языка SQL :: Евгений Моргунов', 9, 4);
insert into book (name, category_id, ordering) values ('PostgreSQL 11. Мастерство разработки :: Ганс-Юрген Шениг', 9, 5);
insert into book (name, category_id, ordering) values ('NoSQL Distilled :: Мартин Фаулер', 9, 6);
insert into book (name, category_id, ordering) values ('Hacking for Dummies :: Kevin Beaver', 10, 1);
insert into book (name, category_id, ordering) values ('Безопасность web-приложений :: Эндрю Хоффман', 10, 2);
insert into book (name, category_id, ordering) values ('Хакинг: искусство эксплойта. 2-е изд. :: Эриксон Джон', 10, 3);
insert into book (name, category_id, ordering) values ('Высоконагруженные приложения. Программирование, масштабирование, поддержка :: Мартин Клеппман', 11, 1);
insert into book (name, category_id, ordering) values ('Облачные архитектуры. Разработка устойчивых и экономичных облачных приложений :: Том Лащевски, Камаль Арора, Эрик Фарр, Пийюм Зонуз', 11, 2);
insert into book (name, category_id, ordering) values ('System Design :: Алекс Сюй', 11, 3);
insert into book (name, category_id, ordering) values ('Разработка интерфейсов. Паттерны проектирования. 3-е издание :: Дженифер Тидвелл, Чарли Брюэр, Эйнн Валенсия', 12, 1);
insert into book (name, category_id, ordering) values ('Accessibility for Everyone :: Laura Kalbag', 12, 2);
insert into book (name, category_id, ordering) values ('Refactoring UI :: Adam Wathan, Steve Schoger', 12, 3);
insert into book (name, category_id, ordering) values ('Pro HTML5 Accessibility :: Joshue O. Connor', 12, 5);
insert into book (name, category_id, ordering) values ('CSS для профи :: Грант Кит', 12, 6);
insert into book (name, category_id, ordering) values ('Интерфейс. Новые направления в проектировании компьютерных систем :: Джеф Раскин', 12, 7);
insert into book (name, category_id, ordering) values ('Hands-On Machine Learning with Scikit-Learn, Keras, and Tensorflow: Concepts, Tools, and Techniques to Build Intelligent Systems. 2nd Edition :: Aurélien Géron', 13, 1);
insert into book (name, category_id, ordering) values ('Python и машинное обучение :: Себастьян Рашка', 13, 2);
insert into book (name, category_id, ordering) values ('Python и машинное обучение. Машинное и глубокое обучение с использованием Python, scikit-learn и TensorFlow 2 :: Мирджалили Вахид, Рашка Себастьян', 13, 3);
insert into book (name, category_id, ordering) values ('Практическая статистика для специалистов Data Science. 2-е изд. :: Брюс Питер', 13, 4);
insert into book (name, category_id, ordering) values ('Глубокое обучение на Python. 2 издание :: Шолле Франсуа', 13, 5);
insert into book (name, category_id, ordering) values ('Deep Learning for Vision Systems :: Mohamed Elgendy', 13, 6);
insert into book (name, category_id, ordering) values ('Python для сложных задач: наука о данных и машинное обучение :: Вандер Плас Дж.', 13, 7);
insert into book (name, category_id, ordering) values ('Data Science Наука о данных с нуля :: Грас Джоэл', 13, 8);
insert into book (name, category_id, ordering) values ('Python и анализ данных :: Маккини Уэс', 13, 9);
insert into book (name, category_id, ordering) values ('An Introduction to Statistical Learning :: Gareth James, Daniela Witten, Trevor Hastie, Rob Tibshirani (для новичков с матбазой)', 13, 10);
insert into book (name, category_id, ordering) values ('Bayesian Reasoning and Machine Learning :: David Barber (для продвинутых)', 13, 11);
insert into book (name, category_id, ordering) values ('Pattern Recognition and Machine Learning :: Кристофер Бишоп (для продвинутых)', 13, 12);
insert into book (name, category_id, ordering) values ('LLVM. Инфраструктура для разработки компиляторов :: Аулер Рафаэль, Лопес Бруно Кардос', 14, 1);
insert into book (name, category_id, ordering) values ('Время UNIX. A History and a Memoir :: Брайан Керниган', 14, 2);
insert into book (name, category_id, ordering) values ('Git для профессионального программиста :: Штрауб Бен, Чакон Скотт', 14, 3);
insert into book (name, category_id, ordering) values ('Теоретический минимум по Computer Science. Все что нужно программисту и разработчику :: Фило Владстон Феррейра', 14, 4);
insert into book (name, category_id, ordering) values ('Микросервисы и контейнеры Docker :: Парминдер Сингх Кочер', 14, 5);
insert into book (name, category_id, ordering) values ('Практическое использование Vim :: Дрю Нейл', 14, 6);
insert into book (name, category_id, ordering) values ('IT как оружие :: Брэд Смит, Кэрол Энн Браун', 14, 7);
insert into book (name, category_id, ordering) values ('Ум программиста. Как понять и осмыслить любой код :: Фелин Херманс', 14, 8);
insert into book (name, category_id, ordering) values ('Делай как в Google. Разработка программного обеспечения :: Райт Хайрам, Маншрек Том', 14, 9);
insert into book (name, category_id, ordering) values ('Код: тайный язык информатики :: Чарльз Петцольд', 14, 10);
insert into book (name, category_id, ordering) values ('Структура и Интерпретация Компьютерных Программ :: Сассман Джеральд Джей, Абельсон Харольд', 14, 11);
insert into book (name, category_id, ordering) values ('Проект «Феникс». Роман о том, как DevOps меняет бизнес к лучшему :: Спаффорд Джордж, Бер Кевин', 14, 12);
insert into book (name, category_id, ordering) values ('Microservices Patterns :: Chris Richardson', 14, 13);
insert into book (name, category_id, ordering) values ('Наш код. Ремесло, профессия, искусство :: Егор Бугаенко', 15, 1);
insert into book (name, category_id, ordering) values ('Программист-прагматик. Путь от подмастерья к мастеру :: Э. Хант, Д. Томас', 15, 2);
insert into book (name, category_id, ordering) values ('Джедайские техники :: Дорофеев Максим', 15, 3);
insert into book (name, category_id, ordering) values ('Визуализируйте работу :: Доминика Деграндис', 15, 4);
insert into book (name, category_id, ordering) values ('Как пасти котов :: Рейнвотер Дж. Ханк', 15, 5);
insert into book (name, category_id, ordering) values ('Мифический человеко-месяц, или Как создаются программные системы :: Брукс Фредерик', 15, 6);
insert into book (name, category_id, ordering) values ('Deadline. Роман об управлении проектами :: Том Демарко', 15, 7);
insert into book (name, category_id, ordering) values ('Сделано. Проектный менеджмент на практике :: Скотт Беркун', 15, 8);
insert into book (name, category_id, ordering) values ('Думай медленно… решай быстро :: Даниэль Канеман', 15, 9);
insert into book (name, category_id, ordering) values ('Стартап: Настольная книга основателя :: Стив Бланк, Боб Дорф', 15, 10);
insert into book (name, category_id, ordering) values ('От нуля к единице :: Питер Тиль', 15, 11);
insert into book (name, category_id, ordering) values ('Бизнес с нуля :: Эрик Рис', 15, 12);
insert into book (name, category_id, ordering) values ('Rework: бизнес без предрассудков :: Джейсон Фрайд, Дэвид Хайнемайер Хенссон', 15, 13);
insert into book (name, category_id, ordering) values ('Как привести дела в порядок :: Дэвид Аллен', 15, 14);
insert into book (name, category_id, ordering) values ('Не заставляйте меня думать :: Стив Круг', 16, 1);

insert into bot_user(telegram_id, is_admin) values (623100489, True)

insert into voting_type(id, vote_type_name) values (1, 'category')
insert into voting_type(id, vote_type_name) values (2, 'book')
