INSERT INTO book_category (name, ordering) VALUES ('Как писать хорошо, а нехорошо не писать', 10);
INSERT INTO book_category (name, ordering) VALUES ('Тестирование', 20);
INSERT INTO book_category (name, ordering) VALUES ('Python', 30);
INSERT INTO book_category (name, ordering) VALUES ('Go', 40);
INSERT INTO book_category (name, ordering) VALUES ('Rust', 50);
INSERT INTO book_category (name, ordering) VALUES ('JavaScript', 60);
INSERT INTO book_category (name, ordering) VALUES ('Linux ', 70);
INSERT INTO book_category (name, ordering) VALUES ('Алгоритмы', 80);
INSERT INTO book_category (name, ordering) VALUES ('БД', 90);
INSERT INTO book_category (name, ordering) VALUES ('Безопасность', 100);
INSERT INTO book_category (name, ordering) VALUES ('Большие системы', 110);
INSERT INTO book_category (name, ordering) VALUES ('Фронтенд', 120);
INSERT INTO book_category (name, ordering) VALUES ('Machine Learning', 130);
INSERT INTO book_category (name, ordering) VALUES ('Another interesting', 140);
INSERT INTO book_category (name, ordering) VALUES ('Софт-скилы, проектная работа', 150);
INSERT INTO book (name, category_id, ordering) VALUES ('Чистый код :: Роберт Мартин', 1, 1);
INSERT INTO book (name, category_id, ordering) VALUES ('Идеальный программист :: Роберт Мартин', 1, 2);
INSERT INTO book (name, category_id, ordering) VALUES ('Чистая архитектура :: Роберт Мартин', 1, 3);
INSERT INTO book (name, category_id, ordering) VALUES ('Идеальная работа :: Роберт Мартин', 1, 4);
INSERT INTO book (name, category_id, ordering) VALUES ('Совершенный код :: Стив Макконнелл', 1, 5);
INSERT INTO book (name, category_id, ordering) VALUES ('Паттерны объектно-ориентированного проектирования :: Гамма Эрих, Хелм Ричард, Джонсон Роберт, Влиссидес Джон', 1, 6);
INSERT INTO book (name, category_id, ordering) VALUES ('Head First. Паттерны проектирования. 2-е издание :: Эрик Фримен, Элизабет Робсон', 1, 7);
INSERT INTO book (name, category_id, ordering) VALUES ('Шаблоны корпоративных приложений :: Мартин Фаулер', 1, 8);
INSERT INTO book (name, category_id, ordering) VALUES ('Шаблоны интеграции корпоративных приложений :: Бобби Вульф, Грегор Хоп', 1, 9);
INSERT INTO book (name, category_id, ordering) VALUES ('Предметно-ориентированное проектирование :: Эрик Эванс', 1, 10);
INSERT INTO book (name, category_id, ordering) VALUES ('Реализация методов предметно-ориентированного проектирования :: Вон Вернон', 1, 11);
INSERT INTO book (name, category_id, ordering) VALUES ('Пять строк кода :: Кристиан Клаусен', 1, 12);
INSERT INTO book (name, category_id, ordering) VALUES ('Рефакторинг. Улучшение существующего кода :: Мартин Фаулер ', 1, 13);
INSERT INTO book (name, category_id, ordering) VALUES ('Программируй & типизируй :: Влад Ришкуция', 1, 14);
INSERT INTO book (name, category_id, ordering) VALUES ('A Philosophy of Software Design, 2nd edition :: John Ousterhout', 1, 15);
INSERT INTO book (name, category_id, ordering) VALUES ('Эффективная работа с унаследованным кодом :: Майкл Физерс', 1, 16);